version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend_jackblack:v13
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend_jackblack:v13
    ports:
      - "80:80"
    depends_on:
      - backend
